### ISSUE TITLE
Use namespace for styling

### ISSUE THREAD

**Issue by lak-16** [webex/react-widgets#1042]
Am loading space widget in my application. I have seen some styling set for html elements without any namespace in space widget.
Ex: ul { margin-left: 1rem }

If i don't set any styles for ul in my application, it is effecting my application styles as well. It would be great if you use namespace to apply styles. So that it won't effect applications which are using space widget.

**Comment by adamweeks** [comment]
Please contact developer support at https://developer.webex.com/support for further assistance with this issue.
