### ISSUE TITLE
Video and Audio Toggle Not Working 

### ISSUE THREAD

**Issue by breno12321** [webex/react-widgets#1080]
I was developing an embebed solution and during tests I found out that if you toggle off video or audio input it doesn't come back after I turn it on again. You can test it [here](https://code.s4d.io/widget-demo/production/index.html)

**Comment by etamminga** [comment]
Same experience here

**Comment by breno12321** [comment]
😭

**Comment by adamweeks** [comment]
Please contact developer support at https://developer.webex.com/support for further assistance with this issue.

**Comment by bmeade90** [comment]
This issue still seems to be open.

**Comment by lalli-flores** [comment]
@breno12321, @etamminga , @bmeade90 this issue has now been fixed in version 0.5.0 onwards. If you're using production CDN, it will take a couple weeks to propagate
