### ISSUE TITLE
Missing dependency @formatjs/intl-pluralrules

### ISSUE THREAD

**Issue by saltenhub** [webex/react-widgets#1090]
# Bug report

It seems to me that the dependency for `@formatjs/intl-pluralrules` is missing from `@webex/webex-widget-base`:
```
Failed to compile.

./node_modules/@webex/webex-widget-base/es/index.js
Module not found: Can't resolve '@formatjs/intl-pluralrules/dist/locale-data' in '/home/saltenhub/webex-test/node_modules/@webex/webex-widget-base/es'
```

**Steps to reproduce:**
- Create a react app with `yarn create react-app` (react-scripts current version - v3.4.1)
- Add dependency for any widget, e.g. `yarn add @webex/widget-space` (v0.2.17)
- Import widget for use via `import SpaceWidget from @webex/widget-space`
- `yarn start` to start the development server

**Expected behavior:**
`@formatjs/intl-pluralrules` gets pulled correctly as a dependency on adding the `@webex/widget-space` and does not need to be added to `package.json` manually.

**Interim solution:**
`yarn add @formatjs/intl-pluralrules` solves the issue for me.

**Comment by oborys** [comment]
I have the same issue

**Comment by mchandran** [comment]
Receiving error:- Module not found: Can't resolve '@formatjs/intl-pluralrules/dist/locale-data'
npm add @formatjs/intl-pluralrules  - Didn't solve the issue.

**Comment by jdaly13** [comment]
This should be fixed with the latest PR that has been merged into master
https://github.com/webex/react-widgets/pull/1110

This would be release 0.2.115
