### ISSUE TITLE
Widgets not working: babelHelpers is not defined

### ISSUE THREAD

**Issue by saltenhub** [webex/react-widgets#1091]
# Bug report
I am not able to get any widget working with a current version of create-react-app (react-scripts v3.4.1) - the build finished fine, but when I try to access the page I am running into a reference error:
```
ReferenceError: babelHelpers is not defined
```

![Error message](https://user-images.githubusercontent.com/52566130/82073664-d98a2380-96d9-11ea-9d17-0a6ac1b54c67.png)

**Steps to reproduce:**
- Create a react app with `yarn create react-app` (react-scripts current version - v3.4.1)
- Add dependency for any widget, e.g. `yarn add @webex/widget-space` (v0.2.17)
- Import widget for use via `import SpaceWidget from @webex/widget-space`
- Add @formatjs/intl-pluralrules because of #1090 `yarn add @formatjs/intl-pluralrules`
- `yarn start` to start the development server
- Go to `http://localhost:3000`

**Expected behavior**:
The widget working as described in the documentation.

**Comment by machner** [comment]
Same here - without importing the @webex/widget-space it works fine. We can't get the widget to run even in minimal react app.
![ebabff6c-3f53-4afd-80d9-a0c891150436](https://user-images.githubusercontent.com/40216144/82092225-27faea80-96f9-11ea-9839-9765381036ec.PNG)

**Comment by nhogge** [comment]
I found a workaround...

install babel cli
`npm i @babel/cli -D`

generate the babelHelpers js
`npx babel-external-helpers > babel-helpers.js`

include in your project first. I am using webpack to did the following:
`entry: [
    './src/babel-helpers.js',
    './src/index.js'
  ],`

**Comment by Haas-webquake** [comment]
Thanks for the support !

I have done the first two points, but now I am not sure where in the webpack I should insert the babel-helpers.js.

I found the webpack.config.js in the folder react-scripts/config/. I think this is the right file. I'm posting here a screenshot of my attempt to integrate your code. May I ask you for your support again.

Thanks in advance, best regards

![image](https://user-images.githubusercontent.com/65902178/82812141-9e82af80-9e92-11ea-86d0-dce8dd9342f3.png)

**Comment by jdaly13** [comment]
This should be fixed with the latest PR that has been merged into master
#1110

This would be release 0.2.115
