### ISSUE TITLE
Error with API Joining Space

### ISSUE THREAD

**Issue by gmendiol-cisco** [webex/react-widgets#1098]
Using the code to join a space.  Pass the GuestToken, spaceId and set Destination Type to SpaceId, get following result.  Spinning wheel then get the Conversation Not Found error.  Here is the console message:

Uncaught (in promise) t: Conversation not found
undefined https://conv-a.wbx2.com/conversation/api/v1/conversations/63986c80-bd6d-11ea-9512-678f137a325f
WEBEX_TRACKING_ID: webex-js-sdk_bbcade39-a9d8-4a2d-b924-98d9374d1567_10

**Comment by lalli-flores** [comment]
@gmendiol-cisco, are you passing an access token or a JWT token? The widgets only understand the former

**Comment by gmendiol-cisco** [comment]
You are correct in that I was passing the JWT Token, when I added the exchange and used the Access Token, it worked great.

**Comment by gmendiol-cisco** [comment]
I have another question regarding video.  I've tried initiating video 1:1 or 1:Space from both directions and keep running into this error:

engine.js:252 Uncaught (in promise) TypeError: Cannot read property 'getUserMedia' of undefined
    at Function.value (engine.js:252)
    at engine.js:896

I'm using the production bundle.js and have also tried latest.  I appreciate any guidance you can provide.

**Comment by lalli-flores** [comment]
@gmendiol-cisco, I hope you've figured it out by now 😅  but that error means that you're trying to load the widget in an insecure page. To get access to camera and microphone the page need to be served securely, e.g. HTTPS.
