### ISSUE TITLE
Compilation Failed and getting Error

### ISSUE THREAD

**Issue by ramesh-joshi** [webex/react-widgets#1102]
Hi Team,

I added the SpaceWidget in my react application and when I am trying to compile the application, I am getting this error-

![image](https://user-images.githubusercontent.com/11056602/87348734-0f952980-c50a-11ea-98c7-70dd1f3096b4.png)

This is my code to add the SpaceWidget -

![image](https://user-images.githubusercontent.com/11056602/87348909-597e0f80-c50a-11ea-99cf-23913fdd7e39.png)

**Comment by rsaulat** [comment]
Me to.

**Comment by mchandran** [comment]
Same

**Comment by adamweeks** [comment]
Please contact developer support at https://developer.webex.com/support for further assistance with this issue.
