### ISSUE TITLE
Error with Chrome 84.0.4147.105

### ISSUE THREAD

**Issue by vichychou** [webex/react-widgets#1107]
I have implemented Webex Teams Widgets on my website and tested last week. It worked. 
after few days, we try to open a conversion but get problems.
When I dial someone, I can see my video on screen but can't see other side's video.
In addition, audio and message are fine. 
Even use smartphone or laptop.
BTW, I did't change code in these few days.
After whole testing, I downgrade my chrome version from (84.0.4147.105) to (83.0.4103.116), the widgets is working.

**Comment by adamweeks** [comment]
Please contact developer support at https://developer.webex.com/support for further assistance with this issue.
