### ISSUE TITLE
Space Widget not working when joining a Webex meeting using SIP URL

### ISSUE THREAD

**Issue by Chinese-Dragon** [webex/react-widgets#1112]
I have been trying to integrate the **Webex Space Widget** into a minimal React App with a valid access token and a SIP URL. The UI shows up fine but when I the "call" button. It shows error "Webex cannot connect your call. Please try again." You can see the error image below. 

![Screen Shot 2020-08-11 at 2 53 59 PM](https://user-images.githubusercontent.com/16981650/89957835-4cc60780-dbed-11ea-963c-d9a7a1b7c00c.png)

However, I am able to successfully join the meeting with the same access token and SIP URL using the [Multi Party Calling Demo App](https://js.samples.s4d.io/browser-multi-party-call/#). 

Please help..

**Comment by adamweeks** [comment]
Please contact developer support at https://developer.webex.com/support for further assistance with this issue.
