### ISSUE TITLE
Feature Request : we would like to pass some context(json) to widget

### ISSUE THREAD

**Issue by techie-abhat** [webex/react-widgets#779]
Hi there,

I would like to pass a context to widget given the page on which I am, say would like to pass a json object.  Not sure how to raise a feature request, can you look into it.

Ex, if on page A, I would like to invoke chat agent, then my webhook should know that I am calling from page A + some more info,  

Thanks,
Ashuthosh

**Comment by bzang** [comment]
Hi @techie-abhat, thanks for the feature request!

Can you please give a more detailed example? I'm not sure what you mean when you say "invoke chat agent, then my webhook should know that I am calling from page".

It would be great if you could provide us a step by step description, and maybe propose an update to the widget API that would support your needs.

**Comment by techie-abhat** [comment]
Thanks @bzang 

Just to elaborate using another example, say if a chatbot were there on github.com, the chatbot along with the request should know which page of github am I on.  Am I on 'raise new ticket' page or on explore page.

**Comment by adamweeks** [comment]
Hello, we are tracking feature requests via the developer support channel, if this request is still relevant, please contact us on https://developer.webex.com/

Thanks.
