### ISSUE TITLE
CDN Stylesheet contains globally matching styles

### ISSUE THREAD

**Issue by megamit** [webex/react-widgets#924]
The css contains several styles that match html tags such as `img` `html` `body` which can break styles on existing webpages which forces it to be put in an iframe to protect the rest of the page.
Ideally all styles would be prepended with some class or id to prevent leakage.

**Comment by adamweeks** [comment]
This has been fixed as of version [0.2.10](https://github.com/webex/react-widgets/releases/tag/v0.2.10)
